chs.api-key=${CHS_API_KEY}
spring.thymeleaf.render-hidden-markers-before-checkboxes=true
server.servlet.session.cookie.secure=true
spring.autoconfigure.exclude=org.springframework.boot.security.autoconfigure.SecurityAutoConfiguration,org.springframework.boot.security.autoconfigure.UserDetailsServiceAutoConfiguration
welshLanguage.enabled=false
management.endpoints.enabled-by-default=false
management.endpoints.web.base-path=/auth-code-requests
management.endpoints.web.path-mapping.health=/healthcheck
management.endpoint.health.show-details=never
management.endpoint.health.enabled=true

# Properties required by common-web-java
commonweb.cdn-url=//${CDN_HOST}
commonweb.chs-url=${CHS_URL}
commonweb.piwik-url=${PIWIK_URL}
commonweb.piwik-site-id=${PIWIK_SITE_ID}
commonweb.contactUsUrl=${CONTACT_US_URL}
commonweb.developer-url=${DEVELOPER_URL}

# OpenTelemetry configuration
management.opentelemetry.enabled=${OTEL_LOG_ENABLED:false}
management.opentelemetry.logging.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/logs
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/traces
management.otlp.metrics.export.url=${OTEL_EXPORTER_OTLP_ENDPOINT}/v1/metrics